name: Run a bash command

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run_bash_command:
    name: Run a bash script using github actions
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Run a bash script manually
        run: bash list.sh

    #   - name: Run multiple bash script manually
    #     run: |
    #       pwd
    #       ls -a

    #   - name: Run multiple commands manually
    #     run: bash scripts/bash.sh
